#!/bin/bash

set -e

usage()
{
  echo "process_file -b [bucket] -k [key] file" 
}

while getopts ":b:k:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    k)
      KEY=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

shift $((OPTIND-1))

FILE=$1

if [ -z "$FILE" ]; then
  usage
  exit 1
fi

FILENAME=$(basename "$FILE")

if [ -z "$KEY" ]; then
  KEY=$FILENAME
fi

./s3put -b "$BUCKET" -k "$KEY" "$FILE"
 
./resourceput -d "$BUCKET" "$KEY" 

TYPE=$(./type "$FILE")

case "$TYPE" in
  "Image")
    DIMENSIONS=200x200

    THUMB=$(./thumb -d "$DIMENSIONS" "$FILE")
    ./s3put -b "$BUCKET" -k "__thumbs/$DIMENSIONS/$KEY" -c "image/jpeg" "$THUMB"
    ;;
  "Video")
    DIMENSIONS=200x200

    THUMB=$(./thumbv -d "$DIMENSIONS" "$FILE")
    ./s3put -b "$BUCKET" -k "__thumbs/$DIMENSIONS/$KEY" -c "image/jpeg" "$THUMB"
    ;;
esac

exit 0

