#!/bin/bash

set -e
set -x

USAGE="Usage: resourceput [resource_key] [db_name]"

if [ $# -ne 2 ]; then
  echo "$USAGE"
  exit 1
fi

RESOURCE_KEY=$1
DB_NAME=$2

RESOURCE_NAME=$(basename "$RESOURCE_KEY")

MONGO_HOST="ec2-54-172-64-205.compute-1.amazonaws.com:27017"
MONGO_DB="$DB_NAME"
MONGO_COLLECTION_RESOURCE=resource
MONGO_COLLECTION_FOLDER=folder

# lookup folder_id
FOLDER_KEY=$(dirname "$RESOURCE_KEY")
FOLDER_ID=$(folderput "$FOLDER_KEY")

# upsert key, name, folder_id

mongo --quiet $MONGO_HOST/$MONGO_DB --eval "db.$MONGO_COLLECTION_RESOURCE.update( { key:\"$RESOURCE_KEY\" }, { \$set: { key:\"$RESOURCE_KEY\", name: \"$RESOURCE_NAME\", folder_id: $FOLDER_ID } }, { upsert: true } )"

exit 0

