#!/bin/bash

set -e

USAGE="Usage: s3put [source] [bucket] [key]"

if [ $# -lt 3 ]; then
  echo "$USAGE"
  exit 1
fi

SOURCE=$1
BUCKET=$2
KEY=$3

MD5SUM=$(openssl dgst -md5 -binary "$SOURCE" | openssl enc -base64)

aws s3api put-object --bucket "$BUCKET" --key "$KEY" --body "$SOURCE" --content-md5 $MD5SUM >>/dev/null

echo "$BUCKET/$KEY"

exit 0

