#!/bin/bash

set -e

usage()
{
  echo "Usage: s3put -b [bucket] -f [folder] file1 file2 ..."
}

while getopts ":b:f:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    f)
      FOLDER=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

[ ! -z "$FOLDER" ] && FOLDER=${FOLDER%/}

shift $((OPTIND-1))

while [ $# -gt 0 ]
do
  FILE=$1
  FILENAME="${FILE##*/}"

  MD5SUM=$(openssl dgst -md5 -binary "$FILE" | openssl enc -base64)

  if [ -z "$FOLDER" ]; then
    KEY=$FILENAME
  else
    KEY=$FOLDER/$FILENAME
  fi
  
  aws s3api put-object --bucket "$BUCKET" --key "$KEY" --body "$FILE" --content-md5 $MD5SUM >>/dev/null

  echo "$BUCKET/$KEY"

  shift
done

exit 0

