#!/bin/bash

set -e
set -x
USAGE="Usage: s3vthumb [bucket] [key] [dimensions] [nopad]"

if [ $# -lt 2 ]; then
  echo "$USAGE"
  exit 1
fi

BUCKET=$1
KEY=$2
DIMENSIONS=$3
NOPAD=$4

THUMBS_PREFIX=__thumbs

[ "$WORKING_DIR" = "" ] && WORKING_DIR=/tmp/s3vthumb
mkdir -p $WORKING_DIR

[ "$DIMENSIONS" = "" ] && DIMENSIONS="200x200"

DIRNAME=$(dirname "$KEY")
FILENAME=$(basename "$KEY")
FILENAME_NO_EXTENSION="${FILENAME%.*}"

ORIGINAL=$WORKING_DIR/$FILENAME
FRAME=$WORKING_DIR/frame__$FILENAME_NO_EXTENSION.jpg
THUMB=$WORKING_DIR/thumb__$FILENAME_NO_EXTENSION.jpg

aws s3api get-object --bucket "$BUCKET" --key "$KEY" "$ORIGINAL" 

DURATION=$(avconv -i "$ORIGINAL" 2>&1 | grep Duration | cut -d' ' -f4 | sed s/,//)

SECONDS=$(echo "$DURATION" | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }' | cut -d'.' -f1)

[ $SECONDS -lt 300 ] && SS=30
[ $SECONDS -lt 30 ] && SS=5
[ $SECONDS -lt 5 ] && SS=0

avconv -loglevel quiet -ss $SS -i "$ORIGINAL" -strict experimental -vframes 1 $FRAME

convert "$FRAME" -thumbnail "$DIMENSIONS" -strip -interlace Plane -quality 80 "$THUMB"

aws s3api put-object --bucket "$BUCKET" --key "$THUMBS_PREFIX/$DIMENSIONS/$DIRNAME/$FILENAME.jpg" --body "$THUMB" 

exit 1

rm "$THUMB"
rm "$FRAME"
rm "$ORIGINAL"

exit 0

