#!/bin/bash

set -e

USAGE="Usage: vthumb [original] [dimensions] [nopad]"

if [ $# -lt 1 ]; then
  echo "$USAGE"
  exit 1
fi

ORIGINAL=$1
DIMENSIONS=$2
NOPAD=$3

[ "$DIMENSIONS" = "" ] && DIMENSIONS="200x200"

QUALITY=80

FILENAME=$(basename "$ORIGINAL")

[ "$WORKING_DIR" = "" ] && WORKING_DIR=.

FRAME=$WORKING_DIR/frame__$FILENAME.jpg
THUMB=$WORKING_DIR/thumb__$FILENAME.jpg

DURATION=$(avconv -i "$ORIGINAL" 2>&1 | grep Duration | cut -d' ' -f4 | sed s/,//)

SECONDS=$(echo "$DURATION" | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }' | cut -d'.' -f1)

[ $SECONDS -lt 300 ] && SS=30
[ $SECONDS -lt 30 ] && SS=5
[ $SECONDS -lt 5 ] && SS=0

avconv -loglevel quiet -ss $SS -i "$ORIGINAL" -strict experimental -vframes 1 $FRAME

if [ "$NOPAD" = "" ]; then
  convert "$FRAME" -auto-orient +repage -thumbnail $DIMENSIONS -background white -gravity center -extent $DIMENSIONS -strip -interlace Plane -quality $QUALITY "$THUMB"
else
  convert "$FRAME" -auto-orient +repage -thumbnail $DIMENSIONS -strip -interlace Plane -quality $QUALITY "$THUMB"
fi

echo "$THUMB"

exit 0

